#!/bin/bash
set -x
docker info
docker run --rm --privileged tonistiigi/binfmt:latest --install linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6
docker buildx version
docker buildx create --use --name=multipleplatforms --driver docker-container
docker buildx ls
set +x
docker buildx build --push --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6 -f $DOCKERFILE_PATH -t $IMAGE_NAME . 