FROM debian:stable 

# install dependencies
RUN dpkg --add-architecture armhf && apt-get update \
    && apt-get -y install build-essential autoconf automake libtool pkg-config git bash curl wget cmake \
      libcurl4-openssl-dev libudev-dev libusb-1.0-0-dev libncurses5-dev libz-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /opt/