#!/bin/bash
set -x
export DOCKER_CLI_EXPERIMENTAL=enabled
export DOCKER_BUILDKIT=1
docker run --rm --privileged tonistiigi/binfmt:latest --install all
docker buildx version
docker buildx create --use --name=multipleplatforms --driver docker-container
docker buildx ls
set +x
docker buildx build --push --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6 -f Dockerfile -t kayuii/gcc:base .
docker buildx build --push --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6 -f ./gnu/Dockerfile -t kayuii/gcc:latest .
