#!/bin/bash
set -x
ls /proc/sys
ls /proc/sys/fs
ls /proc/sys/fs/binfmt_misc
docker run --rm --privileged tonistiigi/binfmt:latest --install all
docker buildx version
docker buildx create --use --name=multipleplatforms --driver docker-container
docker buildx ls
set +x
docker buildx build --push --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6 -f $DOCKERFILE_PATH -t $IMAGE_NAME . 