#!/bin/bash
set -x
docker images

docker run --rm --privileged tonistiigi/binfmt:latest --install all
docker buildx version
docker buildx create --use --name=multipleplatforms --driver docker-container --platform linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6
docker buildx inspect --bootstrap
set +x
# docker buildx build --push --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6 -f $DOCKERFILE_PATH -t $IMAGE_NAME . 