#!/bin/bash
set -x
docker images

export DOCKER_CLI_EXPERIMENTAL=enabled

docker run --rm --privileged tonistiigi/binfmt:latest --install all

docker buildx version

docker buildx create --use --name=mybuilder --driver docker-container

docker buildx ls


# docker run --rm --privileged tonistiigi/binfmt:latest --install all
# docker buildx version
# docker buildx create --use --name=multipleplatforms --driver docker-container --platform linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6
# docker buildx inspect --bootstrap
set +x
# docker buildx build --push --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6 -f $DOCKERFILE_PATH -t $IMAGE_NAME . 
docker buildx build --push -f $DOCKERFILE_PATH -t $IMAGE_NAME --platform linux/amd64,linux/arm64 .