FROM debian:stable 

# RUN apt-get update  \
#  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --assume-yes apt-utils 2>&1 | grep -v "debconf: delaying package configuration, since apt-utils is not installed" 

# install dependencies
RUN apt-get update \
    && apt-get -y install build-essential autoconf automake libtool pkg-config git bash curl wget \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /opt/

